### ISSUE TITLE
Comparison of identity management solutions

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#1]
We might want to consider using a 3th party auth provider either temporarily or permanently.

## Amazon Cognito

https://aws.amazon.com/cognito
https://aws.amazon.com/cognito/pricing

AWS differentiates pricing between password/social and SAML/OIDC.

* First 50.000 (pw/social): free
* Next 50.000 (pw/social): $0,0055 / MAU
* First 50.000 (OIDC/SAML): $0,050 / MAU

### Pros

* Cheap to start if you don't need OIDC/SAML

### Cons

* Built for AWS, some features don't make sense if only using Cognito
* Conceptually complex

## Auth0

https://auth0.com
https://auth0.com/pricing

* Free plan
  * 7.000 users
  * No role management
  * Not clear if it supports SSO
* First 10.000: $ 0,0228 / user

### Pros

* DX friendly
* Established provider

### Notable features

* Roles and access management (Might not be useful)

## Clerk

https://clerk.dev
https://clerk.dev/pricing

* Developer: 500 users: free
* Business: $0.02 / MAU

### Pros

* DX friendly

### Notable features

* Multi-session sign-on

### Cons

* Not so established

### Pros

* Full control
* No cost

### Cons

* Security risk
* Development time

**Comment by Moeriki** [comment]
To Review:

* https://supertokens.com/docs/session/introduction
* https://www.keycloak.org/documentation
* https://fusionauth.io/

**Comment by hsluoyz** [comment]
@Moeriki there's another open-source IAM solution called Casdoor, it's relatively new but very promising. It supports a lot of procotols like OAuth 2.0, OIDC, SAML. It also integrates with Casbin's RBAC and ABAC authorization. (Casdoor and Casbin are both from the same open-source community)

- Docs: https://casdoor.org/
- Source code: https://github.com/casdoor/casdoor
- Demo site: https://door.casdoor.com/
