### ISSUE TITLE
As an admin, I want to delete a (sub-)competency, so I can remove incorrect or duplicate entries.

### ISSUE THREAD

**Issue by alexandervFS** [OpenSkool/OpenSkool#10]
Needs more clarity

- [x] Given the user deletes a competency, when the user has pressed the button, then a confirmation window appears that asks the user if they really want to delete the competency.
- [x] Given the confirmation window is shown, when the user confirms that they want to delete the competency, then the competency gets deleted. 
- [x] Given the confirmation window is shown, when the user closes the window because they don't want to delete the competency, the competency does not get deleted. 
- [x] Given the selected competency has sub-competencies, when the user deletes this competency, the competency and its sub-competencies get deleted.
![image](https://user-images.githubusercontent.com/100140906/158079776-d3a75dae-f6d1-469b-a333-e43a05288469.png)

**Comment by alexandervFS** [comment]
Needs more clarity

- [ ] What happens with the subcomponents if the deleted component had children?

**Comment by Moeriki** [comment]
Deployed to dev.

https://api.dev.openskool.dev/altair

Get random competency.

```graphql
query {
  randomCompetency {
    id
  }
}
```

Delete it.

```graphql
mutation {
  deleteCompetency(id: "__RANDOM__COMPETENCY__ID__") {
    id
  }
}
```

**Comment by Moeriki** [comment]
Tested.

<img width="518" alt="CleanShot 2022-04-27 at 12 15 39@2x" src="https://user-images.githubusercontent.com/38758/165496575-869d6dff-608c-4650-8aba-4d0cd232ddfc.png">

One UX consideration is that we are **irreversibly** removing a potentially big tree of competencies.

This should be reflected in the copy and design better. (CC @pbuytaert)
