### ISSUE TITLE
Als student kan ik media opladen in een e-portfolio

### ISSUE THREAD

**Issue by Djennik** [OpenSkool/OpenSkool#13]
Gebruikers moeten in staat zijn items in hun media bibliotheek op te laden via storage.

- Video
- Afbeelding
- Audio
- Tekst/Document
  - Te bekijken wel files: technische constraint.
  - Tekst Downloaden
  - Tekst bekijken => afhankelijk van browser
- Speech-to-text #20 

Filesizes af te spreken.

Media zijn steeds voorzien van meta-data die zichtbaar zijn in de bibliotheek
- Datum aanmaak/toevoeging (in geval van storage)
- Grootte bestandsfile
- Duur (in geval van video/audio)
- Te checken met beperkingen van Directus => feedback Dieter

**Acceptance Criteria**
- Ik kan een bestand opladen uit mijn device
- Ik kan het opgeladen bestand zien in mijn e-portfolio.
- Ik kan metadata zien van dit bestand in het e-portfolio.

**Comment by Djennik** [comment]
Gebruikers moeten in staat zijn items in hun media bibliotheek op te laden, via captatie of via storage. 

- Video
- Afbeelding
- - Compilaties?
- Audio
- Tekst/Document
- - Te bekijken wel files
- Speech-to-text

Filesizes af te spreken.

**Comment by Moeriki** [comment]
`width` / `height` / `duration` wordt momenteel nog niet afgeleid van de files. Directus gaat dit binnen de CMS wel toevoegen.

https://github.com/directus/directus/pull/6865
