### ISSUE TITLE
Add authorization system

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#152]
Our API needs a base framework to build ABAC authorization on.

## Acceptance Criteria

- Needs investigation

**Comment by shkurata** [comment]
How can I test this?

**Comment by shkurata** [comment]
I followed the code and indeed, all users can `manage all`. It is clear to me how it works, but what should I do with the ticket? Assign it to someone else?

**Comment by shkurata** [comment]
@SiteSeerBE , I assigned the ticket to you, so you can check how the authorization system works.
