### ISSUE TITLE
Auto refresh access token

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#153]
We receive an access / refresh / id token from Keycloak on login.

Right now we set a cookie and this user will be logged in as long as the token is valid.

## Acceptance Criteria

- The API transparently refreshes the access token when it is expired or about to expire. The front-end doesn't know about these tokens. All it knows is that there is a valid user session.
- As a user I stay logged in as long as the refresh token is valid.

## Testing steps

- Set the `access token lifespan` on 1 minute (or use the default of 5 minutes)
- Login and wait the amount of time from step 1
- Refresh the page
- You are still logged in
- Wait 30 minutes (that is the default `SSO Session Idle` time)
- Refresh the page 
- You are logged out

**Comment by shkurata** [comment]
**A possible issue found**

Steps to reproduce:

1. Set the access token lifespan to 1 minute
2. Set the session lifetime to 2,3 or more minutes
3. Login and and wait more than the time set on step 2
4. Try to click on a link for mutation of competency or framework
5. You will get an authentication error message
6. Login again and wait 1 minute
7. Try the action from step 4 again
8. You will get the message from step 5

If watch the `refresh_expires_in` variable with a debugger, you will see that it is not refreshed when the `access_token` and `refresh_token` are updated. 

**TODO**: Investigate further the possible reason of this behavior

**Comment by Moeriki** [comment]
I don't know what `refresh_expires_in` refers to. But while testing I found no issues with the `exp` of the access and refresh tokens.

I added the TokenSet to the API. None of the exposed field contain sensitive information.

```gql
{
  currentUser {
    id
    tokenSet {
      accessToken {
        expiresIn
        issuedAgo
      }
      idToken {
        expiresIn
        issuedAgo
      }
      refreshToken {
        expiresIn
        issuedAgo
      }
    }
  }
}
```

```json
{
  "data": {
    "currentUser": {
      "id": "6a29704b-b0de-4a59-8a81-5778efd6b10a",
      "tokenSet": {
        "accessToken": {
          "expiresIn": "5m",
          "issuedAgo": "3s"
        },
        "idToken": {
          "expiresIn": "5m",
          "issuedAgo": "3s"
        },
        "refreshToken": {
          "expiresIn": "30m",
          "issuedAgo": "3s"
        }
      }
    }
  }
}
```
