### ISSUE TITLE
Support key rotation for oauth public key

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#158]
A key rotation on our OAuth server will be desirable for security, once a year, or god forbid in case of security issues.

Our API should add support so that when the key rotates no one gets logged out.

## Prerequisites

- [x] #159

## Acceptance Criteria

This might already be ok. This can be tested by logging in a user and rotating the Realm's keys in Keycloak.

**Comment by shkurata** [comment]
Rotate keys guide: https://www.keycloak.org/docs/latest/server_admin/#rotating-keys

**Comment by Moeriki** [comment]
To rotate keys.

1. Add `rsa-generated` key.
2. Set previous `rsa-generated` to passive.

Tested on dev.
