### ISSUE TITLE
Als gebruiker kan ik de weergave van media rangschikken

### ISSUE THREAD

**Issue by Djennik** [OpenSkool/OpenSkool#16]
Gebruikers kunnen hun media rangschikken op de zichtbare metadata:
- Titel
- Datum aanmaak/toevoeging
- Grootte bestand
- Duur
- Leerartefact (later wanneer artefacten geïmplementeerd zijn)

**Acceptance Criteria**
- Ik kan rangschikken op de voorziene metadata van e-portofolio.

**Comment by Moeriki** [comment]
### Demo

![CleanShot 2021-11-17 at 14 38 29](https://user-images.githubusercontent.com/38758/142211163-ea59633b-4236-4434-aeb4-27df36c44c6a.gif)
