### ISSUE TITLE
Refactor routes

### ISSUE THREAD

**Issue by SiteSeerBE** [OpenSkool/OpenSkool#179]
## Context
Routes are full of scripts and form renders and should only be used for routing.
Because of this many GraphQL queries run even when the "unauthorized" component is displayed.
## Acceptance
- [ ] Routes are mainly used for routing
- [ ] There are separate components for rendering data
- [ ] There are separate components that render forms
- [ ] GraphQL queries are only called when user is authorized to view the route (and associated data)

**Comment by moeriki** [comment]
Listed some concerns and ideas on new branch.

https://github.com/OpenSkool/OpenSkool/blob/refactor-routes-179/app/src/pages/ROUTES.md

Will pick this up again after #208 and #304.
