### ISSUE TITLE
Design button UI component

### ISSUE THREAD

**Issue by SiteSeerBE** [OpenSkool/OpenSkool#189]
## Context

Epic: #200 

Create a button with different states and different colors.

<img width="670" alt="CleanShot 2022-05-06 at 11 43 36@2x" src="https://user-images.githubusercontent.com/38758/167107959-0744b035-690c-4140-af02-5c0517830017.png">

## Acceptance Criteria

- Can be used with or without FormKit

## States

- Disabled state
- Focus state
- Hover state

## Variants

- Style: Primary, Primary-Outline, Secondary
- Size: Normal, Small

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by shkurata** [comment]
OK in DEV.
