### ISSUE TITLE
Design title UI components

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#203]
## Context

Epic: #200 

We already have a few page titles but there's no component yet.

<img width="304" alt="CleanShot 2022-05-06 at 11 51 31@2x" src="https://user-images.githubusercontent.com/38758/167109153-c7fd6c85-03e8-4803-abb0-474e62518331.png">

<img width="237" alt="CleanShot 2022-05-06 at 12 24 00@2x" src="https://user-images.githubusercontent.com/38758/167114377-7ec9975c-b778-46de-be58-e3f5745a8f26.png">

## Acceptance Criteria

- A new `ui-title` component
  - Semantics is decoupled from design
  - A popular pattern in Vue for implementing variable semantics in a component library is using an `is`.
  - Eg. `<ui-title is="h1" class="text-xl">Hello World</ui-title>`
- A new `ui-subtitle` component

## Variants

- Size: [A scale is already implemented.](https://github.com/OpenSkool/OpenSkool/blob/main/app/windi.config.ts#L17)

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by shkurata** [comment]
OK in DEV.
