### ISSUE TITLE
Design ordered list UI component

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#204]
## Context

Epic: #200 

<img width="427" alt="CleanShot 2022-05-06 at 12 01 58@2x" src="https://user-images.githubusercontent.com/38758/167110967-20279123-5f95-4b00-b9d4-9d721ea93fb8.png">

Props / emits are suggestive.

## Acceptance criteria

- New `ui-ordered-list` component
- Update competency and competency framework list to use this component

## Props

- `reorderControls: boolean`
  - If #208 is not yet done, this will have to be hard-coded to `true` in its implementation because we won't have a way to toggle the property yet.

## Emits

- `swapCompetency(leftCompetencyId: string, rightCompetencyId: string)`

## States

- Reorder state (based on props)

## References

- https://openskool.projects.calibrate.be/v02/
- https://wmartins.github.io/2019/05/a-deep-dive-into-children-in-vue/
- https://www.joshwcomeau.com/css/styling-ordered-lists-with-css-counters/

**Comment by Moeriki** [comment]
I think you misunderstood the ticket. No design has been done at all. See screenshot.

**Comment by shkurata** [comment]
Where do I get this arrow icon from? I don't find it in Remix icons.

**Comment by Moeriki** [comment]
Use any arrow.
