### ISSUE TITLE
Design menu UI component

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#207]
## Context

Epic: #200 

<img width="289" alt="CleanShot 2022-05-06 at 15 50 50@2x" src="https://user-images.githubusercontent.com/38758/167146421-80f87ad8-c4d9-4e89-80b4-7279a6ffbdc8.png">

The screenshot is just for reference. In this ticket we're designing a generic ui menu component. Not implement the user menu specifically. The content can be used however as a reference for what should be possible within the menu.

## Acceptance criteria

- A reusable `ui-menu` component
- No toggle button within the UI component

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by shkurata** [comment]
Ok in Dev.
