### ISSUE TITLE
Develop / design main content layout

### ISSUE THREAD

**Issue by moeriki** [OpenSkool/OpenSkool#208]
## Context

Epic: #200 

We need a layout for our competency management. I'm not sure what to call this layout because I have no idea how all the other pages will look. Maybe something like `management-layout`. This layout can be incorporated into the routes.

Left: Action Menu, Filter (Out of scope)
Right: Content

<img width="1297" alt="CleanShot 2022-05-20 at 11 05 46@2x" src="https://user-images.githubusercontent.com/38758/169494787-61bbbe20-9505-4c41-8e21-124bdcb27840.png">

Fullscreen: content
Bottom right: Action Menu Toggle Button

<img width="427" alt="CleanShot 2022-05-20 at 11 07 49@2x" src="https://user-images.githubusercontent.com/38758/169495118-07fe6c23-0e47-4358-8718-206d88be8038.png">

## Acceptance Criteria

- We have a layout components that render the main content for competency management
- The layout is responsible for deciding how to render its children. Specifically the action menu is very different on mobile.
- The competency management implements this layout in its routes.
- Create / edit / delete competency are actions in the action menu.
- The re-ordering of competencies feature is
  - hidden behind an action menu
  - shielded by an ability
 
## Out of Scope

- Filter. Because competency management doesn't involve filtering.
- Table content. In the screenshot is a user management table because we don't have screenshots for desktop competency management.

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by SiteSeerBE** [comment]
Caveats 
- Styles are provisional
- didn't move anything back to routes
- delete is still part of component actions
- sort is a toggle. Do we need a confirm button?
