### ISSUE TITLE
Configure color tokens

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#212]
## Context

Epic: #200 

<img width="764" alt="CleanShot 2022-05-06 at 12 29 15@2x" src="https://user-images.githubusercontent.com/38758/167115153-2410c6e4-77f2-4155-a391-365c5b4953f6.png">

## Acceptance criteria

- [Configure windi colors](https://windicss.org/utilities/general/colors.html#reuse-colors)

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by shkurata** [comment]
It seems that the `primary` and the `caution` groups have the same colors. 
https://github.com/OpenSkool/OpenSkool/blob/26f10601023e0570cbf36d4c59d141306f01edba/app/windicss/tokens.ts

**Comment by Moeriki** [comment]
I added an entry in #236.
