### ISSUE TITLE
Design icon button UI component

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#213]
## Context

Epic: #200 

<img width="35" alt="CleanShot 2022-05-06 at 12 32 52@2x" src="https://user-images.githubusercontent.com/38758/167115644-a1e3f665-91ae-4a8a-ae90-f6ecb7a82f49.png">

## Acceptance criteria

- A new `ui-icon-button` component with `button` semantics

## Props

- `label: string` accessible label

## States

- Focus state
- Hover state

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by shkurata** [comment]
OK in DEV.

![Image](https://user-images.githubusercontent.com/10957413/167804677-b81a28f3-4ecd-473f-b0c5-5be140c2898d.png)
