### ISSUE TITLE
Design radio input component

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#214]
## Context

Epic: #200 

<img width="572" alt="CleanShot 2022-05-06 at 12 55 04@2x" src="https://user-images.githubusercontent.com/38758/167118695-4d42a577-971a-4801-820d-62ddecc1f72c.png">

## Acceptance criteria

- Can be used with or without FormKit

## States

- Disabled state
- Focus state

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by shkurata** [comment]
The disabled state cannot be achieved.
