### ISSUE TITLE
Design checkbox input component

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#215]
## Context

Epic: #200 

<img width="561" alt="CleanShot 2022-05-06 at 12 57 20@2x" src="https://user-images.githubusercontent.com/38758/167118994-b74c5c2d-aec3-4553-9034-f7f7f9f923ba.png">

## Acceptance Criteria

- Can be used with or without FormKit

## States

- Disabled state
- Focus state

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by shkurata** [comment]
The disabled state cannot be achieved.
