### ISSUE TITLE
Design main left navigation UI component and implement

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#217]
## Context

Epic: #200 

<img width="285" alt="CleanShot 2022-05-06 at 15 32 21@2x" src="https://user-images.githubusercontent.com/38758/167141850-f82113ae-0cad-497b-9213-de5d875f80a5.png">

There's no design from our designer. We referenced the navigation on the material design website for inspiration.

Second example is made with our content.
!(https://user-images.githubusercontent.com/33690553/167161100-54c025fa-9b8e-4926-aa4e-bd6397ad2634.png)

## Acceptance Criteria

- A `ui-main-nav` component (semantic `nav`)
- We might re-use `ui-subtitle` for the section headers. Otherwise `ui-main-nav-header`.
- `ui-main-nav-link` (semantic `a`)
- Implement current menu into main navigation

## Out of Scope

- Collapsing sub-sections. We'll create separate ticket when we need them.
- Visible active section (Stage Kontich)
- Hover/on tab effect (Evalueren)
- Badges (Open)

## References

- https://m3.material.io

**Comment by pbuytaert** [comment]
![Screenshot 2022-05-06 170747](https://user-images.githubusercontent.com/33690553/167161100-54c025fa-9b8e-4926-aa4e-bd6397ad2634.png)

**Comment by Moeriki** [comment]
There are no hover or focus states for the menu items.

**Comment by Moeriki** [comment]
Looks good 👍

**Comment by Moeriki** [comment]
## To Do

- Add section with header / divider

**Comment by Moeriki** [comment]
Ok.
