### ISSUE TITLE
Design UI modal component

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#234]
## Context

Epic: #200 

<img width="534" alt="CleanShot 2022-05-11 at 15 51 56@2x" src="https://user-images.githubusercontent.com/38758/167866177-82e62883-e137-4edb-a3f9-37a2cf5e1b55.png">

In this ticket we're designing a generic UI modal component.

## Acceptance criteria

- A reusable `ui-modal` component
- No toggle button within the UI component

## References

- https://openskool.projects.calibrate.be/v02/

**Comment by shkurata** [comment]
Ok in Dev.
