### ISSUE TITLE
Left navigation improvements

### ISSUE THREAD

**Issue by pbuytaert** [OpenSkool/OpenSkool#259]
Improvements after #217 

- Accessibility: add keyboard access
- On mobile, the menu should collapse after selecting a menu item

Design:
- Separator line thickness: 1px io 3px
- only border on the right side
- Background color is white
- Entire column should be white (now the length of the menu changes in function of the length of the content.
-  the OpenSkool logo should be added
- "OpenSkool" shouldn't have the same weight as the title

**Comment by SiteSeerBE** [comment]
The menu slides nicely while the content pane jumps. Would it be possible to make that slide as well?

**Comment by SiteSeerBE** [comment]
All specified requirements have been met. Thank you for making main content slide as well.
