### ISSUE TITLE
As a student, I want to see the list of available intern positions of a specific internship, so that I can decide which options I'd like to check.

### ISSUE THREAD

**Issue by chavajo** [OpenSkool/OpenSkool#262]
## Prerequisites

- [x] #261

**CHANCE**

**FOR WHICH DEVICES**

**EXTRA DATA**

Mockup: https://design.penpot.app/#/view/65e09db0-c7b5-11ec-ab9e-75f6b8214121?page-id=65e09db1-c7b5-11ec-ab9e-75f6b8214121&section=interactions&index=1

**ACCEPTANCE CRITERIA**

1. When Student selects the internship name in the main menu, then she lands on the intern positions available page.
2. Student sees this info in each card:
- organization's logo
- organization's name
- intern position description

## To do

- [x] Api: Add `InternshipPosition` field `summary`
- [x] Api: Create database model for internship positions
- [x] Api: Implement `Internship` resolver for `availablePositions`
- [x] App: Add grid with available positions to my-internships page

## Query

```gql
{
  myInternshipInstances {
    internship {
      availablePositions {
        summary
        organisation {
          name
        }
      }
    }
  }
}
```

## Out of scope

- Company logo: #332

**Comment by shkurata** [comment]
Where do we store the logo's?

**Comment by moeriki** [comment]
Looks good and merged to main.

## To do

- Add and assert abilities so all data can be read only be minimal permission.
- Check internship position seed.
- (Optional) Join "internship" fixtures together.
