### ISSUE TITLE
As a student, I want to be able choose the priority of an intern position I want to apply for, so that approver know which intern position is my first, second and third option.

### ISSUE THREAD

**Issue by chavajo** [OpenSkool/OpenSkool#273]
## Prerequisites

- [ ] #263

**CHANGE**

**FOR WHICH DEVICES**

**EXTRA DATA**

- Business rules to be added later on.
- Mockup: https://design.penpot.app/#/view/65e09db0-c7b5-11ec-ab9e-75f6b8214121?page-id=65e09db1-c7b5-11ec-ab9e-75f6b8214121&section=interactions&index=6

**ACCEPTANCE CRITERIA**

1. Student can select one of the intern positions:
- The application shows a modal.
- Student can click on the drop-down menu _Keuze_.
- Student can choose priority for the intern position she's checking.
- Student can select one of the 3 priority options the drop-down menu _Keuze_.

## To do

- [ ] Api: Implement `applyForPriorityInternshipPosition` mutation
- [ ] App: Add priority select and implement submit

## Mutation

```gql
mutation {
  applyForPriorityInternshipPosition(instanceId: "", positionId: "", priority: 1) {
    position: node {
      id
    }
    priority
  }
}
```

**Comment by moeriki** [comment]
Integrated into #284.
