### ISSUE TITLE
Main nav

### ISSUE THREAD

**Issue by moeriki** [OpenSkool/OpenSkool#283]
## Todo

- [x] Structure elements
- [x] Develop behavior
- [x] Design basic positioning
- [x] Add animations

**Comment by SiteSeerBE** [comment]
I would prefer if the animation was also applied on the main div, so it animates together with the menu and doesn't jump.

**Comment by moeriki** [comment]
Yes I know I'd love the same thing but I didn't have time and had to prioritize. Let's keep it open. Anyone can pick this up.

**Comment by shkurata** [comment]
Main div animation falls in the low priority features. So, I'm setting the ticket to `Done`.
