### ISSUE TITLE
Update competency doesn't work

### ISSUE THREAD

**Issue by pbuytaert** [OpenSkool/OpenSkool#292]
Actions:
Browse https://dev.openskool.dev/manage/frameworks/cl3iexr8d00125s4oh2yc7g2v/cl3jzeoff02815s87y4ax9o05/edit
Remove ";"
Click "Update competency"

Result: No error, nothing changed

**Comment by SiteSeerBE** [comment]
**In general "update competency" works.**
**Entering on another page besides https://dev.openskool.dev/manage/frameworks sends you back to the initial landing page.**
- Open https://dev.openskool.dev/manage/frameworks
- Click any competency
- Refresh page
- Click FRAMEWORKS
- Select another competency > you land on refreshed competency
The payload is not taken from URL but from initial refreshed page.
**None of the competencies for "Basiscompetenties leerkracht" can be updated.**
- Try to update one of these competencies > you are redirected without change
Payload is correct.
**Behaviour can not be reproduced on local.**
With similar content update and query work, even for an entries with ";" sign.

**Comment by SiteSeerBE** [comment]
After deleting the initial entry containing the ";"-sign I can no longer reproduce the "can not update"-error. However the refresh error persists.

**Comment by SiteSeerBE** [comment]
On Peters' device updates still don't work. We tried several browsers and several user logins.

**Comment by Moeriki** [comment]
Met @SiteSeerBE verder uitgezocht. Het probleem ligt bij de locales.

Als je een competency maakt in NL en dan update in EN (of omgekeerd) krijgen we de bug. De "update" van de competency in de back-end hield geen rekening met het feit dat hij soms ook create moet doen ipv update.
