### ISSUE TITLE
When my session expires, I should be notified and not being able tot do anything.

### ISSUE THREAD

**Issue by pbuytaert** [OpenSkool/OpenSkool#293]
## Context

As an active user, I should be notified and not being able tot do anything when my session expires so that I don't get confused.

E.G: during testing I was editing a Framework, but it returned an 'unspecified' error. After some trials, I clicked away and noticed then that I was logged out.

## AC

1. Log in with the correct credentials and go to the dashboard page by default (initial with email + password combination)
1. Go to an edit screen
1. Time out the session
1. The edit functionality is disabled
1. Warning appears

## References

- Related: #304

**Comment by moeriki** [comment]
@pbuytaert veel manieren en scopes om rekening mee te houden. Het strikt minimale effort voor aanvaardbaar gedrag is de AC zoals we ze getypt hebben. Dit is ook de inschatting.

Meer tweaks in het gedrag kunnen we evalueren en in dit (+herinschatten) of een ander ticket verder opnemen.

**Comment by shkurata** [comment]
It works as requested.
