### ISSUE TITLE
Fix auth on CloudFlare PR branches

### ISSUE THREAD

**Issue by moeriki** [OpenSkool/OpenSkool#322]
CloudFlare makes look-ahead deploys for our opened PRs. That's super convenient to review output stuff before merging. Sadly login redirect goes back to the main app.

* Preview PR: https://6ef24193.openskool.pages.dev/
* Actual dev: https://dev.openskool.pages.dev/

## AC

- The login flow supports multiple instances.

## How

<img width="1087" alt="CleanShot 2022-06-03 at 11 50 59@2x" src="https://user-images.githubusercontent.com/38758/171831914-de8abcdc-3103-4dda-8b2d-b1ac2da5cde9.png">

https://auth.dev.openskool.dev/admin/master/console/#/realms/os-dev/clients/ae3db9ff-4460-4c56-a36f-12c3bd591a02

- Keyshould should configure allowed redirect URLS
  - `http://dev.openskool.dev/`
  - TODO: `http://*.openskool.dev/`
- OpenId middleware should return source state URL and redirect back to correct domain.

**Comment by SiteSeerBE** [comment]
URL toevoegen zoals in [52a6440] werkt. Ik vind echter niet de juiste setting in de admin om niet naar dev te worden redirected. Zou het kunnen dat het niet om dezelfde admin gaat? 
Login voor CloudFlare gaat naar `https://openskool-api-crkva.ondigitalocean.app/openid/connect?from=` 
Login voor dev gaat naar `https://api.dev.openskool.dev/openid/connect?from=`

**Comment by shkurata** [comment]
https://github.com/keycloak/keycloak/issues/8929#issuecomment-984373519

**Comment by shkurata** [comment]
It works only like this: `https://*`.

**Comment by moeriki** [comment]
We'll move away from CloudFlare and setup deployment pipeline with kubernetes only.
